### ISSUE TITLE
Exercise 5: Task 1: SQL Server Migration Assistant for Oracle is not starting

### ISSUE THREAD

**Issue by SeeratArora23** [microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#41]
[Exercise 5: Task 1:](https://github.com/microsoft/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Migrating%20Oracle%20to%20Azure%20SQL.md#task-1-migrate-the-oracle-database-to-sql-server-2017-using-ssma) Step 1: On your LabVM, launch Microsoft SQL Server Migration Assistant for Oracle from the Start Menu.

**Issue:** SQL Server Migration Assistant for Oracle is not starting as shown below:

![image](https://user-images.githubusercontent.com/86133139/124448493-23334300-dda0-11eb-913a-99559c506a1e.png)

Can we please have a solution to this?

Thanks

**Comment by saimachi** [comment]
Hi @SeeratArora23,

Thanks for bringing this to our attention. I am working on a fix, and I hope to have it ready soon.

**Comment by saimachi** [comment]
Hello @SeeratArora23,

I believe I have found a fix for this issue, which you can find on [my fork](https://github.com/saimachi/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL/tree/patches).

Essentially, I add an extra task to install .NET Framework 4.8 and configure the machine-wide .NET Framework `machine.config` file. In my environment, there was a conflict between SSMA and the Oracle Managed Data Access provider. I completed the data migration with no problems after this fix.

The step to install .NET Framework 4.8 may be unnecessary; I installed it without consulting the error message first. Could you post the **Details** returned when you try to launch SSMA?

@timahenning: In a future test fix, we will likely remove the step of installing Oracle Data Access Components. This will require more testing.

**Comment by sumitmalik51** [comment]
Hi @saimachi ,

I have tried again and facing the same issue again even after installing the .Net framework and updating the machine.config file.
![image](https://user-images.githubusercontent.com/45102602/126196306-43d77d06-cbaf-4707-b45f-6dc51d9087b5.png)

logs:
Exception: One or more errors occurred.
 site: 
 source: 

InnerException #1: The type initializer for 'Microsoft.SSMA.Framework.Oracle.SqlServer.Initializer' threw an exception.
 site: Void EnsureInitialize()
 source: Microsoft.SSMA.Framework.Oracle.SqlServer
   at Microsoft.SSMA.Framework.Oracle.SqlServer.Initializer.EnsureInitialize()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SSMA.GUI.Product.SourceToTarget.Startup.GuiBootstrap`1.<InitializeAsync>d__11.MoveNext()
InnerException #2: The type initializer for 'Microsoft.SSMA.Framework.Oracle.Generic.OracleTypeProcessor' threw an exception.
 site: Microsoft.SSMA.Framework.Oracle.Generic.OracleTypeProcessor get_Instance()
 source: Microsoft.SSMA.Framework.Oracle.Generic
   at Microsoft.SSMA.Framework.Oracle.Generic.OracleTypeProcessor.get_Instance()
   at Microsoft.SSMA.Framework.Generic.Converters.Types.Default.DefaultContainerDescriptor.GetSourceTypeDescriptor(String id)
   at Microsoft.SSMA.Framework.Generic.Converters.Types.Default.DefaultTypeMappingSchemaDescriptor.Read(XNode node, IContainerDescriptor contDescriptor)
   at Microsoft.SSMA.Framework.Generic.Converters.Types.Default.DefaultContainerDescriptor.ReadSchemaDescriptors(XNode node, IDictionary`2 descriptors)
   at Microsoft.SSMA.Framework.Generic.Converters.Types.Default.DefaultContainerDescriptor.Read(XNode node)
   at Microsoft.SSMA.Framework.Oracle.SqlServer.Initializer.AddContainerDescriptor(SqlServerVersion serverVersion, String descriptorXml)
   at Microsoft.SSMA.Framework.Oracle.SqlServer.Initializer.InitContainerDescriptor()
   at Microsoft.SSMA.Framework.Oracle.SqlServer.Initializer.Initialize()
   at Microsoft.SSMA.Framework.Oracle.SqlServer.Initializer..cctor()
InnerException #3: The type initializer for 'Microsoft.SSMA.Framework.Generic.Logging.Logger' threw an exception.
 site: Microsoft.SSMA.Framework.Generic.Logging.Logger get_GenericLogger()
 source: Microsoft.SSMA.Framework.Generic.Factories
   at Microsoft.SSMA.Framework.Generic.Logging.Logger.get_GenericLogger()
   at Microsoft.SSMA.Framework.Oracle.Generic.OracleTypeProcessor..cctor()
InnerException #4: Configuration system failed to initialize
 site: Void PrepareConfigSystem()
 source: System.Configuration
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   at System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
   at System.Diagnostics.DiagnosticsConfiguration.Initialize()
   at System.Diagnostics.DiagnosticsConfiguration.get_IndentSize()
   at System.Diagnostics.TraceInternal.InitializeSettings()
   at System.Diagnostics.TraceInternal.get_Listeners()
   at System.Diagnostics.Trace.get_Listeners()
   at Microsoft.SSMA.Framework.Generic.Logging.Logger..cctor()
InnerException #5: Section or group name 'oracle.manageddataaccess.client' is already defined. Updates to this may only occur at the configuration level where it is defined. (C:\Program Files\Microsoft SQL Server Migration Assistant for Oracle\bin\SSMAforOracle.exe.Config line 4)
 site: Void ThrowIfErrors(Boolean)
 source: System.Configuration
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)

**Comment by saimachi** [comment]
Hi @sumitmalik51,

Thanks for your response. Did you remove all three of the references to `oracle.manageddataaccess.client`? If so, you can test the debugging measures below.

I managed to uninstall the Oracle Data Access Components by following the procedure below, and then reinstall it **without installing any .NET providers at the machine-wide level.** After this, I ensured that the lab's core tools (dbForge, SSMA, and the sample app) worked. However, I found that dbForge does not work if ODAC is uninstalled, or if it is not installed at the machine-wide level. However, please let me know if dbForge works for you if you don't install ODAC at the machine-wide level. 

1. Launch the Oracle Universal Installer (type in Universal Installer into the Start button)
2. Select **Deinstall Products**
3. Select **Oracle Data Access Components for Oracle Client 12.2.0.1.0** below the Oracle home

![odac-uninstall-1](https://user-images.githubusercontent.com/37318129/126259370-395eae4b-5690-41ae-9312-b29fd88f8869.png)

4. Select **Remove**
5. Confirm the removal (select **Yes**)

![odac-uninstall-2](https://user-images.githubusercontent.com/37318129/126259638-2db03602-6a1d-41d0-b7d5-d4f6c96399d7.png)

6. Install the proper version of ODAC again.
7. Ensure that you do not select **Configure ODP.NET and/or Oracle Providers for ASP.NET at machine-wide level.**

![odac-install-1](https://user-images.githubusercontent.com/37318129/126263867-400d9031-6757-4920-b9c2-f0b4059db42e.png)

As I mentioned, after uninstalling ODAC and restarting the machine, I was able to launch SSMA and connect to the local Oracle instance without any issues. The sample app functioned, and I could create the ADO.NET Entity Data models with the migrated SQL Server 2017. However, if dbForge does not function, I will need to retain the current approach of editing `machine.config`.

**Comment by sumitmalik51** [comment]
Thanks for the information @saimachi, I will give a try right now and let you know if It works

**Comment by timahenning** [comment]
Hi @sumitmalik51, we cannot duplicate the your issue.  Please respond back by tomorrow or we will have to close this issue.

Thanks.
